server:
  port: 8102

spring:
  application:
    name: knowledge-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
